name: Build and Deploy
on:
  workflow_dispatch:
    inputs:
      commitMessage:
        description: 'Commit message'
        default: ""
jobs:
  main:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lastest src and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
        
      - name: Install npm
        run: npm install
      
      - name: Build
        run: npm run build
        env:
          CI: false
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          REACT_APP_GOOGLE_OAUTH2_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_OAUTH2_CLIENT_ID }}
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
          commit-message: "${{ github.event.inputs.commitMessage }}\nDeploying to gh-pages from @${{ github.sha }}"